In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [2]:
A = range(0,1000000)
B = range(0,1000000)
C = [0]*1000000

In [3]:
%%timeit
for i in range(0,1000000):
    C[i] = A[i]+B[i]

1 loop, best of 3: 273 ms per loop


In [6]:
%%timeit
C = np.array(A)+np.array(B)

1 loop, best of 3: 219 ms per loop


### Starting with numpy arrays

In [7]:
arr = np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [9]:
type(arr), arr.shape, arr.ndim, arr.dtype,arr.size, arr.nbytes

(numpy.ndarray, (2, 2), 2, dtype('int32'), 4, 16)

In [11]:
arr = np.arange(0,20,4)
arr

array([ 0,  4,  8, 12, 16])

In [13]:
arr = np.arange(0,-20,-4)
arr

array([  0,  -4,  -8, -12, -16])

In [15]:
arr = np.fromfunction(lambda x,y: 4*x+3*y,(2,4))
arr

array([[  0.,   3.,   6.,   9.],
       [  4.,   7.,  10.,  13.]])

In [16]:
arr = np.random.randint(1,100,(4,4))
arr

array([[23, 38, 74, 82],
       [72, 29, 65, 82],
       [65, 40, 51, 83],
       [65, 31, 17, 73]])

In [18]:
arr = np.linspace(0,100,5)
arr

array([   0.,   25.,   50.,   75.,  100.])

### Accessing arrays elements

In [20]:
arr = np.arange(0,20,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
arr[2:-2], arr[-1:0:-1]

(array([ 4,  6,  8, 10, 12, 14]), array([18, 16, 14, 12, 10,  8,  6,  4,  2]))

In [25]:
arr = np.random.randint(1,100,(4,4))
arr

array([[84, 83, 19, 41],
       [95, 95, 52, 28],
       [43,  2, 79, 95],
       [22,  5,  7, 42]])

In [28]:
arr[2,3], arr[1:3,2:4],arr[:,2]

(95, array([[52, 28],
        [79, 95]]), array([19, 52, 79,  7]))

In [29]:
arr = np.random.randint(1,100,(2,4,4))
arr

array([[[93, 18, 25, 88],
        [94, 17, 55, 40],
        [23, 20, 78, 38],
        [63, 48, 94, 79]],

       [[48,  5, 93,  3],
        [94, 93, 36, 65],
        [ 9, 94, 11, 72],
        [42, 31, 53, 94]]])

In [30]:
arr[:,:,3]

array([[88, 40, 38, 79],
       [ 3, 65, 72, 94]])

### Boolean Indexing

In [32]:
arr = np.arange(0,40,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [33]:
arr>25

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True], dtype=bool)

In [34]:
arr[arr>25]

array([26, 28, 30, 32, 34, 36, 38])

### Fancy Indexing

In [35]:
arr = np.random.randint(1,100,(4,4))
arr

array([[50, 76, 82, 95],
       [66, 11, 75, 90],
       [41, 95, 45, 69],
       [17,  2, 80, 70]])

In [36]:
arr[[0,1,2],[2,3,1]]

array([82, 90, 95])

### Changing Array Shapes

In [50]:
A = np.random.randint(1,20,(4,4))
B = np.random.randint(1,20,(4,4))
A,B

(array([[13,  8, 14,  3],
        [ 9,  8, 18, 14],
        [13,  4,  4,  2],
        [ 9, 15,  5,  5]]), array([[14, 16,  1, 16],
        [12, 17,  2, 12],
        [14, 11,  3, 13],
        [17, 10, 14,  5]]))

In [38]:
A.reshape((2,8)) #will not change orig array

array([[18, 16,  2, 18, 19, 18, 16,  1],
       [18,  9, 17, 16,  5, 17, 15, 10]])

In [39]:
A

array([[18, 16,  2, 18],
       [19, 18, 16,  1],
       [18,  9, 17, 16],
       [ 5, 17, 15, 10]])

In [40]:
C = A  #just an alias

In [41]:
C[1,1]

18

In [42]:
C[1,1] = 100
A

array([[ 18,  16,   2,  18],
       [ 19, 100,  16,   1],
       [ 18,   9,  17,  16],
       [  5,  17,  15,  10]])

In [43]:
C = A.copy() #make a copy of existing array

In [44]:
C[1,1] = 2
A

array([[ 18,  16,   2,  18],
       [ 19, 100,  16,   1],
       [ 18,   9,  17,  16],
       [  5,  17,  15,  10]])

In [45]:
C

array([[18, 16,  2, 18],
       [19,  2, 16,  1],
       [18,  9, 17, 16],
       [ 5, 17, 15, 10]])

In [46]:
A.resize(2,8) #will change orig array
A

array([[ 18,  16,   2,  18,  19, 100,  16,   1],
       [ 18,   9,  17,  16,   5,  17,  15,  10]])

In [48]:
A.ravel() #gives flatened array

array([ 18,  16,   2,  18,  19, 100,  16,   1,  18,   9,  17,  16,   5,
        17,  15,  10])

In [49]:
A.flatten()

array([ 18,  16,   2,  18,  19, 100,  16,   1,  18,   9,  17,  16,   5,
        17,  15,  10])

In [51]:
np.hstack((A,B)) #side by side stack

array([[13,  8, 14,  3, 14, 16,  1, 16],
       [ 9,  8, 18, 14, 12, 17,  2, 12],
       [13,  4,  4,  2, 14, 11,  3, 13],
       [ 9, 15,  5,  5, 17, 10, 14,  5]])

In [52]:
np.vstack((A,B)) #one below the other stack

array([[13,  8, 14,  3],
       [ 9,  8, 18, 14],
       [13,  4,  4,  2],
       [ 9, 15,  5,  5],
       [14, 16,  1, 16],
       [12, 17,  2, 12],
       [14, 11,  3, 13],
       [17, 10, 14,  5]])

In [53]:
np.dstack((A,B)) #depth stack

array([[[13, 14],
        [ 8, 16],
        [14,  1],
        [ 3, 16]],

       [[ 9, 12],
        [ 8, 17],
        [18,  2],
        [14, 12]],

       [[13, 14],
        [ 4, 11],
        [ 4,  3],
        [ 2, 13]],

       [[ 9, 17],
        [15, 10],
        [ 5, 14],
        [ 5,  5]]])

### Vectorization and Broadcasting

In [54]:
X = np.random.randint(1,10,(4,4))
Y = np.random.randint(1,10,(1,4))
X,Y

(array([[6, 8, 7, 9],
        [5, 5, 9, 1],
        [1, 3, 5, 3],
        [8, 9, 7, 9]]), array([[7, 6, 8, 5]]))

In [58]:
B = np.array([1,2,3,4]).reshape((1,4))
B
print(B.shape)

(1, 4)


In [59]:
X+Y #makes 4 copies of Y array

array([[13, 14, 15, 14],
       [12, 11, 17,  6],
       [ 8,  9, 13,  8],
       [15, 15, 15, 14]])

### Element wise functions

In [61]:
X = np.array([10,20,30,40])
np.sin(X)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316])

In [65]:
X = np.random.randint(1,100,(4,4))
X

array([[53, 32,  5, 55],
       [63, 53, 43, 50],
       [88, 36, 39, 43],
       [30, 42, 38, 98]])

In [66]:
np.sqrt(X)

array([[ 7.28010989,  5.65685425,  2.23606798,  7.41619849],
       [ 7.93725393,  7.28010989,  6.55743852,  7.07106781],
       [ 9.38083152,  6.        ,  6.244998  ,  6.55743852],
       [ 5.47722558,  6.4807407 ,  6.164414  ,  9.89949494]])

In [67]:
X = np.array([3,5,1,6,7,3])
np.argmax(X)

4

In [68]:
X = np.array([3,5,1,6,7,3])
np.argsort(X)

array([2, 0, 5, 1, 3, 4], dtype=int64)

### Aggregation Functions

In [69]:
X

array([3, 5, 1, 6, 7, 3])

In [70]:
X.max()

7

In [71]:
X = np.random.randint(1,100,(4,4))
X.max(axis=0)

array([97, 70, 37, 92])

### Question 1

In [80]:
%%timeit
# using numpy
nums = np.arange(1,100001)
mseven = nums[nums%7 == 0]
summ = np.sum(mseven)
summ

1000 loops, best of 3: 389 µs per loop


In [81]:
%%timeit
#using list
numl = range(1,100001)
sevenm = [num for num in numl if num%7 == 0]
summ = sum(sevenm)
summ

100 loops, best of 3: 4.44 ms per loop


### Question 2

In [83]:
x = np.arange(1,101)
x1 = 100*x**2
x2 = x**3
ind = np.argmax(x1>x2)
ind

0

### Question 3

In [86]:
arr = np.random.randint(1,1000,(5,5))
arr

array([[ 60,  59, 242,  70, 490],
       [794, 827, 880, 361, 979],
       [ 53, 616, 878, 771, 545],
       [559,  18, 303, 954, 472],
       [407, 206,  65, 432, 663]])

In [97]:
sub = np.diag(arr[:],k=1)
sub
element = np.max(sub)
element

880

### Question 5

In [106]:
X = np.random.randint(1,10,(10,10))
X

array([[8, 7, 6, 6, 1, 6, 5, 5, 1, 4],
       [3, 8, 3, 7, 5, 7, 5, 8, 9, 7],
       [8, 4, 2, 8, 6, 6, 5, 7, 3, 4],
       [5, 6, 2, 2, 2, 5, 1, 8, 3, 4],
       [4, 1, 1, 5, 3, 8, 7, 7, 7, 9],
       [9, 4, 5, 5, 5, 1, 5, 2, 3, 2],
       [5, 7, 4, 5, 9, 9, 2, 6, 9, 5],
       [4, 6, 3, 2, 7, 3, 6, 9, 1, 8],
       [4, 2, 5, 2, 1, 9, 2, 2, 9, 5],
       [5, 3, 4, 1, 2, 4, 2, 3, 1, 2]])

In [107]:
X-X.mean(axis=0) / X.std(axis=0)

array([[ 5.19694045,  4.84473638,  3.66666667,  4.1161358 , -0.58515158,
         3.6631134 ,  2.9480433 ,  2.6749215 , -0.38443731,  1.76393202],
       [ 0.19694045,  5.84473638,  0.66666667,  5.1161358 ,  3.41484842,
         4.6631134 ,  2.9480433 ,  5.6749215 ,  7.61556269,  4.76393202],
       [ 5.19694045,  1.84473638, -0.33333333,  6.1161358 ,  4.41484842,
         3.6631134 ,  2.9480433 ,  4.6749215 ,  1.61556269,  1.76393202],
       [ 2.19694045,  3.84473638, -0.33333333,  0.1161358 ,  0.41484842,
         2.6631134 , -1.0519567 ,  5.6749215 ,  1.61556269,  1.76393202],
       [ 1.19694045, -1.15526362, -1.33333333,  3.1161358 ,  1.41484842,
         5.6631134 ,  4.9480433 ,  4.6749215 ,  5.61556269,  6.76393202],
       [ 6.19694045,  1.84473638,  2.66666667,  3.1161358 ,  3.41484842,
        -1.3368866 ,  2.9480433 , -0.3250785 ,  1.61556269, -0.23606798],
       [ 2.19694045,  4.84473638,  1.66666667,  3.1161358 ,  7.41484842,
         6.6631134 , -0.0519567 ,  3.6749215 